import warnings
warnings.filterwarnings("ignore")
import os
os.environ["LANGCHAIN_TRACING_V2"] = "false"
import re
import chromadb
from collections import Counter
from datetime import datetime
from sentence_transformers import SentenceTransformer
from langchain_groq import ChatGroq
from dotenv import load_dotenv
import time

load_dotenv()

llm = ChatGroq(
    model="llama-3.1-8b-instant",
    api_key=os.getenv("GROQ_API_KEY"),
    temperature=0.1,
    max_tokens=250
)

print("Loading RAG knowledge base...")
chroma_client = chromadb.PersistentClient(
    path="../project2-rag-chatbot/oracle_vectordb"
)
collection = chroma_client.get_collection("oracle_knowledge")
embedder = SentenceTransformer("all-MiniLM-L6-v2")
print(f"Loaded {collection.count()} knowledge chunks")

def scanner_agent(log_path: str) -> dict:
    print("AGENT 1 SCANNER RUNNING")
    try:
        with open(log_path, "r") as f:
            content = f.read()
        errors = Counter(re.findall(r"ORA-\d+", content))
        result = {
            "log_path": log_path,
            "total_errors": sum(errors.values()),
            "unique_errors": len(errors),
            "error_counts": dict(errors),
            "scanned_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        print(f"Found {result['total_errors']} total errors")
        for code, count in errors.most_common():
            print(f"  {code}: {count} times")
        return result
    except FileNotFoundError:
        return {"error": f"File not found: {log_path}"}

def analyst_agent(scanner_result: dict) -> dict:
    print("AGENT 2 ANALYST RUNNING")
    if "error" in scanner_result:
        return {"error": scanner_result["error"]}
    error_counts = scanner_result.get("error_counts", {})
    diagnoses = {}
    severity_scores = {
        "ORA-04031": 25,
        "ORA-12541": 40,
        "ORA-01555": 15,
        "ORA-00060": 10,
        "ORA-00600": 35,
    }
    health_score = 100
    for error_code, count in error_counts.items():
        print(f"Analyzing {error_code} ({count}x)...")
        q_vector = embedder.encode([error_code]).tolist()
        results = collection.query(
            query_embeddings=q_vector, n_results=2)
        context = "\n".join(results["documents"][0])
        prompt = f"You are an Oracle DBA expert. Error: {error_code} occurred {count} times. Context: {context}. Give CAUSE, FIX, SEVERITY in 3 lines."
        try:
            response = llm.invoke(prompt)
            diagnosis = response.content
            time.sleep(3)
        except Exception:
            diagnosis = "CAUSE: Unknown\nFIX: Check Oracle docs\nSEVERITY: UNKNOWN"
        diagnoses[error_code] = {"count": count, "diagnosis": diagnosis}
        deduction = severity_scores.get(error_code, 10)
        health_score -= min(deduction * count, deduction * 2)
        print(f"  Diagnosis complete")
    health_score = max(0, round(health_score))
    if health_score >= 90:
        grade = "A HEALTHY"
    elif health_score >= 75:
        grade = "B GOOD"
    elif health_score >= 60:
        grade = "C NEEDS ATTENTION"
    elif health_score >= 40:
        grade = "D CRITICAL"
    else:
        grade = "F EMERGENCY"
    return {
        "diagnoses": diagnoses,
        "health_score": health_score,
        "grade": grade,
        "total_errors": scanner_result["total_errors"],
        "unique_errors": scanner_result["unique_errors"]
    }

def reporter_agent(analyst_result: dict, db_name: str = "PRODDB") -> dict:
    print("AGENT 3 REPORTER RUNNING")
    if "error" in analyst_result:
        return {"error": analyst_result["error"]}
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    filename = f"incident_report_{db_name}_{timestamp}.txt"
    lines = []
    lines.append("=" * 60)
    lines.append("ORACLE DATABASE INCIDENT REPORT")
    lines.append("Generated by Multi-Agent AI System")
    lines.append("=" * 60)
    lines.append(f"Database : {db_name}")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("-" * 60)
    lines.append("HEALTH SUMMARY")
    lines.append("-" * 60)
    lines.append(f"Score : {analyst_result['health_score']}/100")
    lines.append(f"Grade : {analyst_result['grade']}")
    lines.append(f"Total Errors  : {analyst_result['total_errors']}")
    lines.append(f"Unique Errors : {analyst_result['unique_errors']}")
    lines.append("-" * 60)
    lines.append("DETAILED DIAGNOSIS")
    lines.append("-" * 60)
    for error_code, data in analyst_result["diagnoses"].items():
        lines.append(f"[{error_code}] occurred {data['count']} time(s)")
        lines.append(data["diagnosis"])
        lines.append("")
    lines.append("-" * 60)
    lines.append("Powered by: LangChain + RAG + Llama 3 + ChromaDB")
    lines.append("GitHub: github.com/geekycloud2026/agentic-ai-journey")
    lines.append("=" * 60)
    report = "\n".join(lines)
    with open(filename, "w") as f:
        f.write(report)
    print(report)
    return {
        "filename": filename,
        "health_score": analyst_result["health_score"],
        "grade": analyst_result["grade"],
        "report": report
    }
